/**
 * Identifies the signed-in Clerk user with PostHog, fires session lifecycle
 * events, and registers super-properties on every identity change.
 *
 * Rules:
 * - Only fires when Clerk `isLoaded && isSignedIn && user.id` is truthy.
 * - `funnel_sign_up_completed` is guarded by a sessionStorage key so it fires
 *   at most once per browser session (not once per page load).
 * - `app_user_identified` fires on every successful identify call.
 * - `app_user_signed_out` fires BEFORE `posthog.reset()` on sign-out.
 * - Identity is reset on sign-out via `resetIdentity()`.
 * - Super-properties registered: `app_version`, `is_signed_in`, `platform`.
 *   `daemon_status` is intentionally excluded — follow-up ticket pending.
 *
 * device_id super-property (#2633):
 * - Fetches GET /api/v1/daemons once per sign-in to determine device count.
 * - N == 1: registers `device_id` super-property with the single device's ID.
 * - N != 1: calls unregisterSuperProperty('device_id') — zero devices means no
 *   pairing has occurred; more than one means the property is ambiguous across
 *   devices and must not be attached to all events (Ray canonical verdict Q4).
 * - On sign-out: unregisterSuperProperty('device_id') is called BEFORE
 *   resetIdentity() — posthog.reset() clears distinct_id which would orphan
 *   the super-property; unregister must precede reset (ordering is load-bearing).
 * - No PII is sent — device_id is an opaque UUID generated by the daemon, not
 *   a user identifier.
 */
import { useEffect, useRef } from 'react';
import { useUser, useAuth } from '@clerk/react';
import {
  trackEvent,
  identifyUser,
  resetIdentity,
  startSessionReplay,
  stopSessionReplay,
  registerSuperProperties,
  unregisterSuperProperty,
} from '../services/analytics';
import { listDaemons } from '../services/api/bffDaemons';

const SESSION_KEY = 'vaultmtg_ph_funnel_sign_up_completed_fired';

// app_version comes from Vite build-time injection; fallback to 'unknown' per
// Ray adj. #5 — do NOT fail-build if the env var is absent.
const APP_VERSION: string =
  (import.meta.env.VITE_APP_VERSION as string | undefined) ?? 'unknown';

// platform is always 'desktop' for the SPA served at app.vaultmtg.app.
const PLATFORM = 'desktop' as const;

export function usePostHogIdentity(): void {
  const { isLoaded, isSignedIn, user } = useUser();
  const { getToken } = useAuth();
  const identifiedRef = useRef(false);

  useEffect(() => {
    if (!isLoaded) return;

    if (isSignedIn && user?.id) {
      if (!identifiedRef.current) {
        identifyUser(user.id);
        // Enable session replay now that we have a confirmed signed-in user.
        // Recording is disabled at init time and only starts here.
        startSessionReplay();
        identifiedRef.current = true;

        // Register super-properties for every subsequent event in this session.
        // Narrowed set per Ray adj. #3: daemon_status excluded (follow-up ticket).
        registerSuperProperties({
          app_version: APP_VERSION,
          is_signed_in: true,
          platform: PLATFORM,
        });

        // Fire app_user_identified on every successful identify.
        // NOTE: user_id is intentionally omitted — frontend hashing pending.
        trackEvent({
          name: 'app_user_identified',
          properties: { auth_method: 'email' },
        });

        // Fire funnel_sign_up_completed once per session.
        if (!sessionStorage.getItem(SESSION_KEY)) {
          trackEvent({
            name: 'funnel_sign_up_completed',
            properties: {
              auth_method: 'email',
              user_id: user.id,
            },
          });
          sessionStorage.setItem(SESSION_KEY, '1');
        }

        // Fetch device list and register/unregister device_id super-property.
        // N == 1: register device_id (unambiguous single device).
        // N != 1: unregister device_id (none paired yet, or ambiguous multi-device).
        // Runs async after identify so it never blocks the identify path.
        void (async () => {
          try {
            const token = await getToken();
            if (!token) return;
            const { devices } = await listDaemons(token);
            if (devices.length === 1) {
              registerSuperProperties({ device_id: devices[0].device_id });
            } else {
              unregisterSuperProperty('device_id');
            }
          } catch {
            // Failure to fetch device list is non-fatal — the super-property
            // simply remains absent. Do not surface to the user.
          }
        })();
      }
    } else if (isLoaded && !isSignedIn) {
      // User signed out — fire lifecycle event, update super-properties,
      // then reset PostHog identity and stop recording.
      if (identifiedRef.current) {
        // app_user_signed_out fires BEFORE posthog.reset() (ordering is
        // critical — reset() clears the distinct_id so the event would be
        // attributed to an anonymous user if called after reset).
        trackEvent({ name: 'app_user_signed_out', properties: {} });

        // Update is_signed_in super-property for any post-signout events.
        registerSuperProperties({
          app_version: APP_VERSION,
          is_signed_in: false,
          platform: PLATFORM,
        });

        // Unregister device_id BEFORE resetIdentity(). posthog.reset() clears
        // the distinct_id — if unregister ran after reset the super-property
        // would be orphaned on the now-anonymous session. Ordering is load-bearing.
        unregisterSuperProperty('device_id');

        stopSessionReplay();
        resetIdentity();
        identifiedRef.current = false;
      }
    }
  }, [isLoaded, isSignedIn, user?.id, getToken]);
}
