import { useState } from 'react';
import { getApiKey, setApiKey } from '@/services/apiClient';
import { SettingItem } from '../';

export interface ApiKeySectionProps {
  /** Called after the key is saved or cleared so the parent can react (e.g. re-init SSE). */
  onKeyChange?: (key: string) => void;
}

/**
 * Settings section that lets the user enter, save, and clear their BFF API key.
 *
 * The key is stored in localStorage via the centralised setApiKey helper so
 * every subsequent request in apiClient.ts picks it up automatically.
 */
export function ApiKeySection({ onKeyChange }: ApiKeySectionProps) {
  const [inputValue, setInputValue] = useState('');
  const [saved, setSaved] = useState(false);
  const hasKey = Boolean(getApiKey());

  const handleSave = () => {
    const trimmed = inputValue.trim();
    if (!trimmed) return;
    setApiKey(trimmed);
    setInputValue('');
    setSaved(true);
    onKeyChange?.(trimmed);
    setTimeout(() => setSaved(false), 2000);
  };

  const handleClear = () => {
    setApiKey('');
    setInputValue('');
    onKeyChange?.('');
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') handleSave();
  };

  return (
    <div className="settings-section">
      <h2 className="section-title">API Key</h2>

      <SettingItem
        label="Current Status"
        description="Whether an API key is stored for authenticating requests to the BFF"
      >
        <span
          className={`connection-badge ${hasKey ? 'status-connected' : 'status-standalone'}`}
          data-testid="api-key-status"
        >
          <span className="status-dot" />
          {hasKey ? 'Key configured' : 'No key — requests will be unauthenticated'}
        </span>
      </SettingItem>

      <SettingItem
        label="API Key"
        description="Enter the API key generated by the BFF. The key is stored locally and sent as Authorization: Bearer on every request."
      >
        <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
          <input
            type="password"
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Paste your API key here"
            className="text-input"
            aria-label="API key input"
            data-testid="api-key-input"
            autoComplete="off"
          />
          <button
            className="action-button"
            onClick={handleSave}
            disabled={!inputValue.trim()}
            data-testid="api-key-save-button"
          >
            {saved ? 'Saved!' : 'Save'}
          </button>
        </div>
      </SettingItem>

      {hasKey && (
        <SettingItem
          label="Remove Key"
          description="Clear the stored API key. Requests will no longer include an Authorization header."
        >
          <button
            className="action-button action-button--danger"
            onClick={handleClear}
            data-testid="api-key-clear-button"
          >
            Remove API Key
          </button>
        </SettingItem>
      )}
    </div>
  );
}
