package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/ramonehamilton/MTGA-Companion/internal/storage/models"
)

// UserRepository provides methods for managing app-level users.
// Queries use PostgreSQL $N placeholders — requires PostgreSQL driver.
type UserRepository interface {
	Create(ctx context.Context, user *models.User) error
	GetByID(ctx context.Context, id int64) (*models.User, error)
	GetByEmail(ctx context.Context, email string) (*models.User, error)
	GetByAPIKey(ctx context.Context, apiKey string) (*models.User, error)
	UpdateSubscriptionStatus(ctx context.Context, id int64, status string) error
	Delete(ctx context.Context, id int64) error
}

type userRepository struct {
	db *sql.DB
}

// NewUserRepository creates a new user repository.
func NewUserRepository(db *sql.DB) UserRepository {
	return &userRepository{db: db}
}

// Create inserts a new user. The api_key is generated by the database default.
func (r *userRepository) Create(ctx context.Context, user *models.User) error {
	query := `
		INSERT INTO users (email, subscription_status, created_at, updated_at)
		VALUES ($1, $2, $3, $4)
		RETURNING id, api_key
	`
	now := time.Now().UTC()
	user.CreatedAt = now
	user.UpdatedAt = now

	return r.db.QueryRowContext(ctx, query,
		user.Email,
		user.SubscriptionStatus,
		user.CreatedAt,
		user.UpdatedAt,
	).Scan(&user.ID, &user.APIKey)
}

// GetByID retrieves a user by primary key.
func (r *userRepository) GetByID(ctx context.Context, id int64) (*models.User, error) {
	query := `
		SELECT id, email, api_key, subscription_status, created_at, updated_at
		FROM users
		WHERE id = $1
	`
	return r.scanUser(r.db.QueryRowContext(ctx, query, id))
}

// GetByEmail retrieves a user by email address.
func (r *userRepository) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	query := `
		SELECT id, email, api_key, subscription_status, created_at, updated_at
		FROM users
		WHERE email = $1
	`
	return r.scanUser(r.db.QueryRowContext(ctx, query, email))
}

// GetByAPIKey retrieves a user by their daemon API key.
func (r *userRepository) GetByAPIKey(ctx context.Context, apiKey string) (*models.User, error) {
	query := `
		SELECT id, email, api_key, subscription_status, created_at, updated_at
		FROM users
		WHERE api_key = $1
	`
	return r.scanUser(r.db.QueryRowContext(ctx, query, apiKey))
}

// UpdateSubscriptionStatus updates a user's subscription tier.
func (r *userRepository) UpdateSubscriptionStatus(ctx context.Context, id int64, status string) error {
	query := `
		UPDATE users
		SET subscription_status = $1, updated_at = $2
		WHERE id = $3
	`
	_, err := r.db.ExecContext(ctx, query, status, time.Now().UTC(), id)
	return err
}

// Delete removes a user and cascades to their accounts.
func (r *userRepository) Delete(ctx context.Context, id int64) error {
	_, err := r.db.ExecContext(ctx, "DELETE FROM users WHERE id = $1", id)
	return err
}

func (r *userRepository) scanUser(row *sql.Row) (*models.User, error) {
	user := &models.User{}
	err := row.Scan(
		&user.ID,
		&user.Email,
		&user.APIKey,
		&user.SubscriptionStatus,
		&user.CreatedAt,
		&user.UpdatedAt,
	)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return user, nil
}
